env:
  - distribution: Ubuntu
    distribution_version: trusty
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

sudo: required
language: ruby
rvm:
  - 2.3.3

before_install:
  - gem install bundler -v 1.13.6
