dist: trusty
sudo: required

language: ruby
rvm:
  - 2.3.3

before_install:
  - sudo add-apt-repository -y ppa:pitti/systemd
  - sudo apt-get update -y
  - sudo apt-get install linux-image-2.6.35-23-generic=2.6.35-23.41ppa1 linux-headers-2.6.35-23-generic=2.6.35-23.41ppa1 linux-headers-2.6.35-23=2.6.35-23.41ppa1
  - sudo apt-get install systemd libpam-systemd systemd-gui systemd-extra-units
  - gem install bundler -v 1.13.6



