env:
  - ANSIBLE_VERSION: "1.9.5"
  - ANSIBLE_VERSION: "2.1.2"
  - ANSIBLE_VERSION: "2.2.1"
  - distribution: Ubuntu
    distribution_version: trusty
    init: /sbin/init

sudo: required
language: ruby
rvm:
  - 2.3.3

before_install:
  - gem install bundler -v 1.13.6
