dist: xenial
# sudo: required
language: ruby

rvm:
  - 2.6.3

before_install:
  - gem install bundler

before_script:
  - export PREV_DIR=$(pwd)
  - sudo apt-get update -qq
  - sudo apt-get install libsystemd-dev
  - >
      [ -f /etc/machine-id ] || cat /dev/urandom | tr -cd 'a-f0-9' | head -c 32 | awk '{ print $1 }' | sudo tee /etc/machine-id
