env:
    # Defaults - Ubuntu 16.04.
    - distribution: ubuntu1604
      init: /sbin/init
      run_opts: "--privileged"

language: ruby
rvm:
  - 2.3.3

before_install:
  - gem install bundler -v 1.13.6
