env:
  - distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""

sudo: required
language: ruby
rvm:
  - 2.3.3

before_install:
  - gem install bundler -v 1.13.6

before_script:
  - 'echo $PATH'
  - 'export PATH=/sbin:$PATH'
