dist: trusty
sudo: required
language: ruby
rvm:
  - 2.3.3

before_install:
  - gem install bundler -v 1.13.6
  - add-apt-repository ppa:pitti/systemd
  - apt-get update
  - apt-get install systemd libpam-systemd systemd-ui


before_script:
  - 'echo $PATH'
  - 'export PATH=/sbin:$PATH'
